version: '3.8'

volumes:
  postgres_data: {}


services:
  db:
#    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_HOST=db
      - POSTGRES_PORT=3513
#      - NAME=postgres
#      - USER=postgres
#      - PASSWORD=samplesecret
#      - PORT=3513
    ports:
      - "3513:5432"
#    networks:
#      - testnet
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    command: bash -c "python3 manage.py migrate && python3 manage.py createsuperuser && python3 manage.py runserver 0.0.0.0:8000"
    environment:
#      - POSTGRES_HOST=db
      - POSTGRES_HOST=db
    depends_on:
      - db
    links:
      - db
    restart: always
    ports:
      - "8000:8000"
#    networks:
#      - testnet

#volumes:
#  pgdata:

#networks:
#  - testnet: